package org.adventure;

import org.adventure.settlement.RoadTile;
import org.adventure.settlement.RoadType;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for RoadTile data model.
 * Validates Builder pattern, upgrade logic, and traffic management.
 */
public class RoadTileTest {
    
    @Test
    public void testRoadTileBuilder() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .type(RoadType.DIRT)
                .createdTick(1000)
                .trafficLevel(25)
                .isAutoGenerated(true)
                .build();
        
        assertEquals(10, road.getX());
        assertEquals(20, road.getY());
        assertEquals(RoadType.DIRT, road.getType());
        assertEquals(1000, road.getCreatedTick());
        assertEquals(25, road.getTrafficLevel());
        assertTrue(road.isAutoGenerated());
    }
    
    @Test
    public void testRoadTileBuilderDefaults() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .build();
        
        assertEquals(RoadType.DIRT, road.getType());
        assertEquals(0, road.getTrafficLevel());
        assertTrue(road.isAutoGenerated()); // Defaults to true
    }
    
    @Test
    public void testRoadTileBuilderPosition() {
        RoadTile road = new RoadTile.Builder()
                .position(15, 25)
                .createdTick(1000)
                .build();
        
        assertEquals(15, road.getX());
        assertEquals(25, road.getY());
    }
    
    @Test
    public void testIncrementTraffic() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .build();
        
        assertEquals(0, road.getTrafficLevel());
        
        road.incrementTraffic(10);
        assertEquals(10, road.getTrafficLevel());
        
        road.incrementTraffic(25);
        assertEquals(35, road.getTrafficLevel());
    }
    
    @Test
    public void testIncrementTrafficCap() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .trafficLevel(95)
                .build();
        
        road.incrementTraffic(10);
        assertEquals(100, road.getTrafficLevel()); // Capped at 100
    }
    
    @Test
    public void testTryUpgradeDirtToStone() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .type(RoadType.DIRT)
                .trafficLevel(49)
                .build();
        
        assertFalse(road.tryUpgrade()); // Not enough traffic
        assertEquals(RoadType.DIRT, road.getType());
        
        road.incrementTraffic(1); // Now at 50
        assertTrue(road.tryUpgrade()); // Should upgrade
        assertEquals(RoadType.STONE, road.getType());
    }
    
    @Test
    public void testTryUpgradeStoneToStone() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .type(RoadType.STONE)
                .trafficLevel(50)
                .build();
        
        assertFalse(road.tryUpgrade()); // Already stone, need 80+ for paved
        assertEquals(RoadType.STONE, road.getType());
    }
    
    @Test
    public void testTryUpgradeStoneToPaved() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .type(RoadType.STONE)
                .trafficLevel(79)
                .build();
        
        assertFalse(road.tryUpgrade()); // Not enough traffic
        assertEquals(RoadType.STONE, road.getType());
        
        road.incrementTraffic(1); // Now at 80
        assertTrue(road.tryUpgrade()); // Should upgrade
        assertEquals(RoadType.PAVED, road.getType());
    }
    
    @Test
    public void testTryUpgradePavedNoUpgrade() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .type(RoadType.PAVED)
                .trafficLevel(100)
                .build();
        
        assertFalse(road.tryUpgrade()); // Already max tier
        assertEquals(RoadType.PAVED, road.getType());
    }
    
    @Test
    public void testAutoUpgradeFlow() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .build();
        
        assertEquals(RoadType.DIRT, road.getType());
        
        // Simulate traffic accumulation
        for (int i = 0; i < 50; i++) {
            road.incrementTraffic(1);
        }
        
        assertTrue(road.tryUpgrade());
        assertEquals(RoadType.STONE, road.getType());
        
        // Continue traffic
        for (int i = 0; i < 30; i++) {
            road.incrementTraffic(1);
        }
        
        assertTrue(road.tryUpgrade());
        assertEquals(RoadType.PAVED, road.getType());
        
        // No more upgrades
        assertFalse(road.tryUpgrade());
    }
    
    @Test
    public void testSchemaVersion() {
        RoadTile road = new RoadTile.Builder()
                .x(10)
                .y(20)
                .createdTick(1000)
                .build();
        
        assertEquals(1, road.getSchemaVersion());
    }
}
