package org.adventure.settlement;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * Represents a road tile in the world that connects structures.
 * Roads are automatically generated when buildings are within 10 tiles.
 * Roads can be upgraded from DIRT → STONE → PAVED as traffic increases.
 * 
 * Design: BUILD_PHASE1.10.x.md → Phase 1.10.2
 */
public final class RoadTile {
    private final int x;
    private final int y;
    private RoadType type;
    private final long createdTick;
    private int trafficLevel;
    private final boolean isAutoGenerated;
    private final int schemaVersion;
    
    @JsonCreator
    public RoadTile(
            @JsonProperty("x") int x,
            @JsonProperty("y") int y,
            @JsonProperty("type") RoadType type,
            @JsonProperty("createdTick") long createdTick,
            @JsonProperty("trafficLevel") int trafficLevel,
            @JsonProperty("isAutoGenerated") boolean isAutoGenerated,
            @JsonProperty("schemaVersion") int schemaVersion) {
        if (type == null) {
            throw new IllegalArgumentException("Road type cannot be null");
        }
        if (createdTick < 0) {
            throw new IllegalArgumentException("Created tick cannot be negative");
        }
        if (trafficLevel < 0 || trafficLevel > 100) {
            throw new IllegalArgumentException("Traffic level must be between 0 and 100");
        }
        
        this.x = x;
        this.y = y;
        this.type = type;
        this.createdTick = createdTick;
        this.trafficLevel = trafficLevel;
        this.isAutoGenerated = isAutoGenerated;
        this.schemaVersion = schemaVersion > 0 ? schemaVersion : 1;
    }
    
    // Getters
    public int getX() { return x; }
    public int getY() { return y; }
    public RoadType getType() { return type; }
    public long getCreatedTick() { return createdTick; }
    public int getTrafficLevel() { return trafficLevel; }
    public boolean isAutoGenerated() { return isAutoGenerated; }
    public int getSchemaVersion() { return schemaVersion; }
    
    // Setters for mutable fields
    public void setType(RoadType type) {
        if (type == null) {
            throw new IllegalArgumentException("Road type cannot be null");
        }
        this.type = type;
    }
    
    public void setTrafficLevel(int trafficLevel) {
        if (trafficLevel < 0 || trafficLevel > 100) {
            throw new IllegalArgumentException("Traffic level must be between 0 and 100");
        }
        this.trafficLevel = trafficLevel;
    }
    
    public void incrementTraffic(int amount) {
        int newLevel = Math.min(100, this.trafficLevel + amount);
        this.trafficLevel = newLevel;
    }
    
    /**
     * Upgrades road to next tier if traffic level is high enough.
     * DIRT (traffic >= 50) → STONE
     * STONE (traffic >= 80) → PAVED
     * 
     * @return true if road was upgraded, false otherwise
     */
    public boolean tryUpgrade() {
        if (type == RoadType.DIRT && trafficLevel >= 50) {
            type = RoadType.STONE;
            return true;
        } else if (type == RoadType.STONE && trafficLevel >= 80) {
            type = RoadType.PAVED;
            return true;
        }
        return false;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RoadTile roadTile = (RoadTile) o;
        return x == roadTile.x && y == roadTile.y;
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(x, y);
    }
    
    @Override
    public String toString() {
        return "RoadTile{" +
                "pos=(" + x + "," + y + ")" +
                ", type=" + type +
                ", traffic=" + trafficLevel +
                ", auto=" + isAutoGenerated +
                '}';
    }
    
    /**
     * Builder for creating RoadTile instances.
     */
    public static class Builder {
        private int x;
        private int y;
        private RoadType type = RoadType.DIRT;
        private long createdTick = 0;
        private int trafficLevel = 0;
        private boolean isAutoGenerated = true;
        private int schemaVersion = 1;
        
        public Builder x(int x) {
            this.x = x;
            return this;
        }
        
        public Builder y(int y) {
            this.y = y;
            return this;
        }
        
        public Builder position(int x, int y) {
            this.x = x;
            this.y = y;
            return this;
        }
        
        public Builder type(RoadType type) {
            this.type = type;
            return this;
        }
        
        public Builder createdTick(long tick) {
            this.createdTick = tick;
            return this;
        }
        
        public Builder trafficLevel(int level) {
            this.trafficLevel = level;
            return this;
        }
        
        public Builder isAutoGenerated(boolean auto) {
            this.isAutoGenerated = auto;
            return this;
        }
        
        public Builder schemaVersion(int version) {
            this.schemaVersion = version;
            return this;
        }
        
        public RoadTile build() {
            return new RoadTile(x, y, type, createdTick, trafficLevel, 
                    isAutoGenerated, schemaVersion);
        }
    }
}
